import type {
  ItemCurrentResponse,
  ItemEditRecord,
  QuestionResponse,
  VersionResponse,
} from "@/shared/api/generated/model";
export const item: ItemCurrentResponse = {
  itemId: 4,
  rowCode: "R1",
  sourceNo: "4",
  seq: 1,
  kind: "Casing",
  kindRaw: "CASING",
  odState: "stated",
  odValue: "4.500",
  odUnit: "in",
  odRaw: "4-1/2 inch",
  wallState: "not_stated",
  weightState: "not_stated",
  grade: "K55",
  gradeRaw: "K55",
  gradeState: "stated",
  connectionState: "not_stated",
  lengthState: "not_stated",
  qtyState: "tba",
  qtyRaw: "TBA",
  dueState: "not_stated",
  placeState: "not_stated",
  history: [],
  rowMatch: null,
};
export const edit: ItemEditRecord = {
  editId: 2,
  itemId: 4,
  field: "qty_value",
  oldValue: "10.00",
  oldState: "numeric",
  newValue: "12.00",
  newState: "numeric",
  reason: "原資料と照合",
  recordedBy: "担当",
  recordedAt: "2026-09-13T01:00:00Z",
  undoneAt: null,
  undoneBy: null,
};
export const question: QuestionResponse = {
  questionId: 5,
  questionCode: "Q1",
  itemId: 4,
  targetField: "grade",
  reason: "材質を照会",
  candidates: null,
  category: "alternative",
  latest: null,
};
export const version: VersionResponse = {
  versionId: 9,
  caseId: 8,
  versionNo: 1,
  currentState: "draft",
  isComplete: false,
  finalizedAt: "2026-09-13T01:00:00Z",
  caseHeader: null,
  counts: {
    itemCount: 2,
    questionItemCount: 1,
    tbaItemCount: 1,
    choiceGroupCount: 1,
    matchedCount: 1,
    editCount: 2,
    editedItemCount: 1,
    unresolvedCount: 2,
  },
  coverageConfirmed: false,
};
