import type {
  ItemCurrentResponse,
  ItemEditRecord,
  QuestionResponse,
  VersionResponse,
} from "@/shared/api/generated/model";
export const item: ItemCurrentResponse = {
  itemId: 4,
  rowCode: "R1",
  sourceNo: "4",
  seq: 1,
  kind: "Casing",
  kindRaw: "CASING",
  odState: "stated",
  odValue: "4.500",
  odUnit: "in",
  odRaw: "4-1/2 inch",
  wallState: "not_stated",
  weightState: "not_stated",
  grade: "K55",
  gradeRaw: "K55",
  gradeState: "stated",
  connectionState: "not_stated",
  lengthState: "not_stated",
  qtyState: "tba",
  qtyRaw: "TBA",
  dueState: "not_stated",
  placeState: "not_stated",
  history: [],
  rowMatch: null,
};
export const edit: ItemEditRecord = {
  editId: 2,
  itemId: 4,
  field: "qty_value",
  oldValue: "10.00",
  oldState: "numeric",
  newValue: "12.00",
  newState: "numeric",
  reason: "原資料と照合",
  recordedBy: "担当",
  recordedAt: "2026-09-13T01:00:00Z",
  undoneAt: null,
  undoneBy: null,
};
export const question: QuestionResponse = {
  questionId: 5,
  questionCode: "Q1",
  itemId: 4,
  targetField: "grade",
  reason: "材質を照会",
  candidates: null,
  category: "alternative",
  latest: null,
};
export const version: VersionResponse = {
  versionId: 9,
  caseId: 8,
  versionNo: 1,
  currentState: "draft",
  isComplete: false,
  finalizedAt: "2026-09-13T01:00:00Z",
  caseHeader: null,
  counts: {
    itemCount: 2,
    questionItemCount: 1,
    tbaItemCount: 1,
    choiceGroupCount: 1,
    matchedCount: 1,
    editCount: 2,
    editedItemCount: 1,
    unresolvedCount: 2,
  },
  coverageConfirmed: false,
};

export const inventory: import("@/shared/api/generated/model").InventoryResponse =
  {
    summary: {
      sourceEntryCount: 5,
      sourceItemCount: 4,
      outputRowCount: 3,
      splitEntryIds: [13],
      excludedEntryIds: [12],
      unmappedEntryIds: [14],
      orphanItemIds: [103],
      multiMappedItemIds: [101],
      inconsistentEntryIds: [15, 98765],
      coverage: null,
    },
    entries: [
      {
        entryId: 11,
        documentId: 1,
        documentFileName: "明細.pdf",
        position: "p.1",
        sourceNo: "1",
        seq: 1,
        excerpt: "CASING 4.500",
        status: "mapped",
        statusDetail: null,
        basis: null,
        linkedItems: [{ itemId: 101, rowCode: "R1" }],
        linkCount: 1,
        judgement: "mapped",
      },
      {
        entryId: 12,
        documentId: 2,
        documentFileName: null,
        position: "p.2",
        sourceNo: null,
        seq: 2,
        excerpt: "<b>https://example.test</b>",
        status: "excluded",
        statusDetail: "除外（脚注）",
        basis: "共通条件を適用",
        linkedItems: [],
        linkCount: 0,
        judgement: "excluded",
      },
      {
        entryId: 13,
        documentId: 1,
        documentFileName: "明細.pdf",
        position: "p.3",
        sourceNo: "3",
        seq: 3,
        excerpt: "候補 A/B",
        status: "split",
        statusDetail: "接続の択一",
        basis: "2候補",
        linkedItems: [
          { itemId: 101, rowCode: "R1" },
          { itemId: 102, rowCode: "R2" },
        ],
        linkCount: 2,
        judgement: "split",
      },
      {
        entryId: 14,
        documentId: 1,
        documentFileName: "明細.pdf",
        position: "p.4",
        sourceNo: "4",
        seq: 4,
        excerpt: "<script>https://example.test</script>",
        status: "unmapped",
        statusDetail: null,
        basis: null,
        linkedItems: [],
        linkCount: 0,
        judgement: "missing",
      },
      {
        entryId: 15,
        documentId: 1,
        documentFileName: "明細.pdf",
        position: "p.5",
        sourceNo: "5",
        seq: 5,
        excerpt: "対応行なし",
        status: "mapped",
        statusDetail: null,
        basis: null,
        linkedItems: [],
        linkCount: 0,
        judgement: "inconsistent",
      },
    ],
    items: [
      {
        itemId: 101,
        rowCode: "R1",
        sourceNo: "1",
        seq: 1,
        groupCode: "G1",
        candidateLabel: "A",
        sourceEntries: [
          { entryId: 11, documentId: 1, position: "p.1", sourceNo: "1" },
          { entryId: 13, documentId: 1, position: "p.3", sourceNo: "3" },
        ],
        hasSource: true,
      },
      {
        itemId: 102,
        rowCode: "R2",
        sourceNo: "3",
        seq: 2,
        groupCode: "G1",
        candidateLabel: "B",
        sourceEntries: [
          { entryId: 13, documentId: 1, position: "p.3", sourceNo: "3" },
        ],
        hasSource: true,
      },
      {
        itemId: 103,
        rowCode: "R3",
        sourceNo: "6",
        seq: 3,
        groupCode: null,
        candidateLabel: null,
        sourceEntries: [],
        hasSource: false,
      },
    ],
  };
