"""foundation: cases documents rule_sets agent_runs versions

Revision ID: bc31bdc005d7
Revises: 
Create Date: 2026-09-10 21:42:25.951757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc31bdc005d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_code', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_code')
    )
    op.create_table('rule_sets',
    sa.Column('rule_version', sa.Text(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conversion_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_version')
    )
    op.create_table('documents',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('read_status', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('pdf','xlsx','eml','text')", name='ck_documents_kind'),
    sa.CheckConstraint("read_status IN ('success','partial','unreadable','encrypted','unsupported')", name='ck_documents_read_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_table('versions',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('prev_version_id', sa.BigInteger(), nullable=True),
    sa.Column('rule_set_id', sa.BigInteger(), nullable=False),
    sa.Column('current_state', sa.Text(), server_default='draft', nullable=False),
    sa.Column('is_complete', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("current_state IN ('draft','staff_checked','review_checked')", name='ck_versions_current_state'),
    sa.CheckConstraint("finalized_at IS NOT NULL OR current_state='draft'", name='ck_versions_finalized_or_draft'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['prev_version_id'], ['versions.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'version_no', name='uq_versions_case_version_no')
    )
    op.create_index(op.f('ix_versions_case_id'), 'versions', ['case_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_set_id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_sec', sa.Numeric(), nullable=True),
    sa.Column('turns', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('stage_detail', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('running','success','failed','stopped')", name='ck_agent_runs_outcome'),
    sa.CheckConstraint("stage IN ('reading','extracting','self_checking','done')", name='ck_agent_runs_stage'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_index(op.f('ix_agent_runs_case_id'), 'agent_runs', ['case_id'], unique=False)
    op.create_table('document_pages',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('locator', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('cells', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'locator', name='uq_document_pages_document_locator')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_table('email_parts',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('part_role', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('from_addr', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('attachment_name', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("part_role IN ('latest_body','quoted_body','postscript','forward_note','attachment')", name='ck_email_parts_part_role'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_parts_document_id'), 'email_parts', ['document_id'], unique=False)
    op.create_table('agent_run_steps',
    sa.Column('agent_run_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_step_id', sa.BigInteger(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('args_digest', sa.Text(), nullable=False),
    sa.Column('args_summary', sa.Text(), nullable=True),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('result_status', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result_status IN ('ok','error','unreadable')", name='ck_agent_run_steps_result_status'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_step_id'], ['agent_run_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'seq', name='uq_agent_run_steps_run_seq')
    )
    op.create_index(op.f('ix_agent_run_steps_agent_run_id'), 'agent_run_steps', ['agent_run_id'], unique=False)
    op.create_table('document_issues',
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_run_id', sa.BigInteger(), nullable=True),
    sa.Column('locator', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("issue_type IN ('unreadable_page','encrypted','unsupported','reference_missing','not_scanned')", name='ck_document_issues_issue_type'),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_issues_document_id'), 'document_issues', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_issues_document_id'), table_name='document_issues')
    op.drop_table('document_issues')
    op.drop_index(op.f('ix_agent_run_steps_agent_run_id'), table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    op.drop_index(op.f('ix_email_parts_document_id'), table_name='email_parts')
    op.drop_table('email_parts')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_agent_runs_case_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_versions_case_id'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('rule_sets')
    op.drop_table('cases')
    # ### end Alembic commands ###
